from settings import *
from colors import *
from sprite import *

# Use our sprite class to generate an image
pikachu = Player("pikachu.png", 100, 100, screen_w // 2, screen_h // 2, 8)

# Add our sprite to a sprite group
all_sprites = pygame.sprite.Group()
all_sprites.add(pikachu)

# Main game loop
playing = True
while playing:
    clock.tick(fps)
    screen.fill(white)
    # Listen to inputs generated by the player
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            playing = False
    all_sprites.update()
    all_sprites.draw(screen)
    pygame.display.update()