from settings import *
from colors import *
from sprite import *

class Game:
    def __init__(self):
        self.screen = pygame.display.set_mode((screen_w, screen_h))
        self.clock = pygame.time.Clock()
        self.playing = True

        self.pikachu = Player("pikachu.png", 100, 100,
                            screen_w // 2, screen_h // 2, 8)
        
        self.all_sprites = pygame.sprite.Group()
        self.all_sprites.add(self.pikachu)
    
    def run(self):
        while self.playing:
            self.clock.tick(fps)
            self.screen.fill(white)
            # Listen to inputs generated by the player
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    pygame.quit()
                    self.playing = False
            self.all_sprites.update()
            self.all_sprites.draw(self.screen)
            pygame.display.update()

game = Game()
game.run()