import pygame
import os
from colors import *

# Initialize pygame
pygame.init()

# Setup an 800x600 game window
screen_w = 800
screen_h = 600
screen = pygame.display.set_mode((screen_w, screen_h))

# Load images
folder = os.path.dirname(__file__)
pikachu_img = pygame.image.load(folder + "/pikachu.png")
pichu_img = pygame.image.load(folder + "/pichu.png")
raichu_img = pygame.image.load(folder + "/raichu.png")

pikachu_rect = pikachu_img.get_rect()
pikachu_rect.center = (screen_w // 2, screen_h // 2)

pichu_rect = pichu_img.get_rect()
pichu_rect.center = (int(screen_w * 0.4), screen_h // 2)

raichu_rect = raichu_img.get_rect()
raichu_rect.center = (int(screen_w * 0.6), screen_h // 2)

# Load Text from the system
font = pygame.font.Font("C:/Windows/Fonts/times.ttf", 48)
# Create the text
text = font.render("Hello world!", True, black)
text_rect = text.get_rect()
text_rect.center = (screen_w // 2, screen_h // 4)

# Main game loop
playing = True
while playing:
    # Listen to inputs generated by the player
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            playing = False
    screen.fill(white)
    screen.blit(text, text_rect)
    screen.blit(pikachu_img, pikachu_rect)
    screen.blit(pichu_img, pichu_rect)
    screen.blit(raichu_img, raichu_rect)
    pygame.display.update()